### ISSUE TITLE
spring-boot 2.5.6，org.apache.dubbo 2.7.23 when using config 'spring.main.lazy-initialization=true' and the @DubboService annotation Class  add '@Lazy(value = false)', start the application,the dubbo producer not register into zk

### ISSUE THREAD

**Issue by kobeleehom** [apache/dubbo#13758]
- [ ] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.23
* Operating System version: win10
* Java version: 1.8

### Steps to reproduce this issue

spring-boot 2.5.6，org.apache.dubbo 2.7.23 when using config 'spring.main.lazy-initialization=true' and the @DubboService annotation Class  add '@Lazy(value = false)', start the application,the dubbo producer not register into zk

Pls. provide [GitHub address] to reproduce this issue.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by AlbumenJ** [comment]
Please try upgrade to 3.2.x

**Comment by laywin** [comment]
This problem also exists in dubbo 3.2.x. The reason is that serviceBeanDifinition currently does not change whether it is lazy due to the existence of @Lazy annotation on the original service. Dubbo service export needs to rely on the initialization of serviceBeanDifinition. If serviceBeanDifinition is lazy, it cannot be exported.

**Comment by AlbumenJ** [comment]
Can you please try submit a reproduceable demo for this issue?

**Comment by laywin** [comment]
> Can you please try submit a reproduceable demo for this issue?

it is easy to reproduceable.

add properties: 
```java
spring.main.lazy-initialization=true
```

define service:
```
@DubboService
@Lazy(value = false)
public class HelloServiceImpl implements HelloService{

	@Override
	public String hello() {
		return "hello";
	}
}
```

HelloService will not register to registration center.

because:

1. it will not set lazy property in ServiceAnnotationPostProcessor when generate serviceBeanDefinition, so it will follow the spring configuration.

2. when serviceBeanDefinition is lazy, it will not register service to configsCache in AbstractConfigManager.

3. when spring context refreshed, HelloService will not be exported because no service in configsCache.


i think serviceBeanDefinition should not be lazy. because when application finish init. it seems no chance to export.

**Comment by ShenFeng312** [comment]
可以分配给我吗 @AlbumenJ
