### ISSUE TITLE
Why not support jackson

### ISSUE THREAD

**Issue by djy6257** [apache/dubbo#13788]
项目使用jackson作为序列化工具，dubbo3额外引入了fastjson2，导致序列化工具重复臃肿，我看官网文档支持很多序列化工具，唯独不支持jackson,是否有自己的考虑
![image](https://github.com/apache/dubbo/assets/61313387/b1f73280-3520-4395-b82c-eef7b330d6c6)

**Comment by shuangpai** [comment]
jackson序列化不支持map这种类型，反序列化会丢失数字等类型的精准对应关系，开启类型标注又太危险。这是我的个人猜测。

**Comment by aofall** [comment]
从dubbo3.2开始只保留了fastjson2、hession、jdk的引入，默认只支持这三种序列化方式，其他的都移动到 dubbo spi extension 中作为可选扩展组件了。

仓库目前已经实现了[Jackson的序列化](https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-serialization-extensions/dubbo-serialization-jackson)，目前因为还在做适配的原因所以暂时还未打包发布maven中央仓库，而且暂时只做了3.2的适配，有需求的话可以自行clone打包引入。之前的版本默认不支持Jackson是基于性能和依赖引入的考虑。

> 反序列化会丢失数字等类型的精准对应关系，开启类型标注又太危险

正如上面所说的，切换序列化需谨慎，而且dubbo目前还没有测试过完全排除fastjson2之后是否会出现预期之外的问题。

-----

Starting from Dubbo 3.2, only the introductions of fastjson2, hession, and jdk are retained, and only these three serialization methods are supported by default. All other serialization methods have been moved to Dubbo SPI Extension as optional extension components.

Currently, the repository has implemented [Jackson serialization](https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-serialization-extensions/dubbo-serialization-jackson). However, it is temporarily not packaged and released to the Maven Central Repository due to ongoing adapter development. Currently, only the adapter for Dubbo 3.2 is available. If you have a need for it, you can clone, package, and introduce it yourself. The previous versions did not support Jackson by default based on considerations of performance and dependency introduction.

> Deserialization can lose the precise correspondence of types such as numbers, and enabling type annotations can be too risky. 

As mentioned above, switching serialization should be cautious, and Dubbo has not yet tested whether there will be unexpected problems after completely excluding fastjson2.
