### ISSUE TITLE
[Bug] Reference. setCheck (false) and consumer:Check: False is set to false, but when the project starts, it still prompts for connection failure

### ISSUE THREAD

**Issue by KongZouXiang** [apache/dubbo#14303]
### Pre-check

- [X] I am sure that all the content I provide is in English.

### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/dubbo/issues?q=is%3Aissue) and found no similar issues.

### Apache Dubbo Component

Java SDK (apache/dubbo)

### Dubbo Version

dubbo.version 3.2.10
spring-boot.version 2.7.10
jdk: 21

![image](https://github.com/apache/dubbo/assets/43474763/62aa16fe-c674-4e9d-8646-c30724a00215)

### Steps to reproduce this issue

null

### What you expected to happen

null

### Are you willing to submit a pull request to fix on your own?

- [ ] Yes I am willing to submit a pull request on my own!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by wcy666103** [comment]
The check happens after the connection to the provider is established and invoker is generated, depending on your Boolean value. As you can see from the screenshot in the Dingtalk group, your exception is due to the connection to the provider.

![bc7fc8a86c4c8233075aae81cab2e7de](https://github.com/apache/dubbo/assets/56506697/e87daa19-a14c-4e25-a88d-5db79549d1bc)

You can do consumer development first as I said with mock.
