### ISSUE TITLE
System property dubbo.registry.address cannot have multiple values

### ISSUE THREAD

**Issue by beiwei30** [apache/dubbo#1725]
In com.alibaba.dubbo.config.AbstractInterfaceConfig#checkRegistry, there's code snippet to handle backward compatibility when there are multiple registry addresses in `dubbo.registry.address`, say: "addr1|addr2":

```java
        // for backward compatibility
        if (registries == null || registries.isEmpty()) {
            String address = ConfigUtils.getProperty("dubbo.registry.address");
            if (address != null && address.length() > 0) {
                registries = new ArrayList<RegistryConfig>();
                String[] as = address.split("\\s*[|]+\\s*");
                for (String a : as) {
                    RegistryConfig registryConfig = new RegistryConfig();
                    registryConfig.setAddress(a);
                    registries.add(registryConfig);
                }
            }
        }
```

but later, appendProperties is called so that the value from `dubbo.registry.address` will override the address value from each RegistryConfig, for registryConfig1, its address becomes from 'addr1' to 'addr1|addr2':

```java
        for (RegistryConfig registryConfig : registries) {
            appendProperties(registryConfig);
        }
```

**Comment by OLPMO** [comment]
Could you provide a minimal demo that can reproduce the problem?@beiwei30 @jasonjoo2010

**Comment by jasonjoo2010** [comment]
> Could you provide a minimal demo that can reproduce the problem?@beiwei30 @jasonjoo2010

After some research I found that it's better to abandon this feature. And we use alternative way to achieve similar configuration by using dubbo.registries and dubbo.registry together. 

Though they are not documented too. (Maybe examples of "dubbo.properties" under several typical scenarios is necessary in document or how-tos)

Why I say it's better to abandon the legacy multiple registries support using the form "registry1|registry2" is because it leads to multiple RegistryConfig beans and may break the design of current protocol.
