### ISSUE TITLE
我自己实现了一个Container，如何在使用com.alibaba.dubbo.container.Main启动应用的时候传递参数进来?

### ISSUE THREAD

**Issue by yjx1045072812** [apache/dubbo#1769]
我自己实现了一个Container，在里面引导启动了我的程序。现在我想借助在java -jar 启动时传递额外参数到MyContainer以覆盖内部参数的效果

**Comment by xiabobin** [comment]
> public static void main(String[] args) {
	//TODU 你的逻辑 
	com.alibaba.dubbo.container.Main.main(args);
}

这种吗？

**Comment by yjx1045072812** [comment]
因为我没有使用spring框架，完全使用api集成，所以想实现自己的容器

**Comment by ralf0131** [comment]
Hi, 

I am afraid that there isn't a way to do so.

Since you can specify multiple container, how can you know which args should go with which container?

e.g. 

```
java -jar my.jar container1 container2 container3
```

How to specify args for container2?

Maybe sth. like this:

```java
java -jar my.jar -container containerA arg1 arg2 -container containerB arg1 arg2 
```

But this may require change for the current code, also you need consider the compatibility. Therefore it is kind of difficult.

Do you have interested in implement this feature? Please let me know.

What I can suggest is using system properties instead for now.

**Comment by yjx1045072812** [comment]
Using system properties is a good solution, but it may not be convenient in the case of automatic integration publishing.
And this:

`java -jar my.jar -container containerA arg1 arg2 -container containerB arg1 arg2 `

This should be the effect I want, I am willing to implement it, but I am afraid I don't have time.
Forgive me for my bad English.

**Comment by ralf0131** [comment]
@yjx1045072812 

1.  Implement that feature don't require your English but coding skill :)
2. Your English is totally understandable, so don't be afraid of that! You can also add Chinese after English to describe your ideas.

You can implement it whenever you have time!

**Comment by scy251147** [comment]
@yjx1045072812  @ralf0131  都是中国人，说啥外文。

**Comment by ralf0131** [comment]
@scy251147 Dubbo is a global community. Please understand the users varies from all over the world.
