### ISSUE TITLE
add features list to README

### ISSUE THREAD

**Issue by kimmking** [apache/dubbo#2142]
I guess adding features list to README, just like other Apache projects, then everyone can know dubbo canbe used to do something, include those they need.

**Comment by ralf0131** [comment]
I've added a short feature list to README, and personally I would like to keep the README simple and concise, so that user won't be frustrated. 

So would you please given an example or send a pull request and let's discuss it.

**Comment by ralf0131** [comment]
Hi, is this still sort of issue to discuss?

**Comment by KishkinJ10** [comment]
sir I am a beginner can I work on this?

**Comment by AlbumenJ** [comment]
> sir I am a beginner can I work on this?

Sure! Pls go ahead

**Comment by Sid672** [comment]
@kimmking, @AlbumenJ  features list is already added in README.md this issue is should be closed.

These features are already present after Architecture.

# Features
- Transparent interface based RPC
- Intelligent load balancing
- Automatic service registration and discovery
- High extensibility
- Runtime traffic routing
- Visualized service governance
