### ISSUE TITLE
dubbo配置支持多协议，不能在service指定其中某一种协议--附详细错误提示

### ISSUE THREAD

**Issue by fuhao715** [apache/dubbo#2781]
_Originally posted by @beiwei30 in https://github.com/apache/incubator-dubbo/issues/2695#issuecomment-433802992_

## Environment
Dubbo version: 2.6.2
Operating System version: mac
Java version: 1.8

#### protocol1:
name: dubbo
id: dubbo
status: server

#### protocol2:
id: rest
name: rest
status: server
server: tomcat

contextpath: api/swift/v1
extension: com.alibaba.dubbo.rpc.protocol.rest.support.LoggingFilter

##服务注释

```java
@service(
version = "${demo.service.version}",
application = "${dubbo.application.id}",
registry = "${dubbo.registry.id}",
protocol = "dubbo"
)
public class DefaultDemoService implements DemoService{
……………………
}
```

问题： 无法指定服务的协议类型。

建议：
service注解标明协议类型，则是指定类型暴露，否则按照配置协议类型暴露

工程启动错误提示如下：
===2018-11-09 15:44:00.450 INFO com.alibaba.dubbo.config.spring.beans.factory.annotation.DubboConfigBindingBeanPostProcessor Line:85 - The properties of bean [name : protocol1] have been binding by prefix of configuration properties : dubbo.protocols.protocol1
===2018-11-09 15:44:00.456 INFO com.alibaba.dubbo.config.spring.beans.factory.annotation.DubboConfigBindingBeanPostProcessor Line:85 - The properties of bean [name : protocol2] have been binding by prefix of configuration properties : dubbo.protocols.protocol2
===2018-11-09 15:44:01.194 INFO org.springframework.boot.devtools.autoconfigure.OptionalLiveReloadServer Line:57 - LiveReload server is running on port 35729
===2018-11-09 15:44:01.322 WARN org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext Line:558 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '**ServiceBean:defaultDemoService:com.swift.boot.dubbo.demo.api.DemoService:${demo.service.version}': Cannot resolve reference to bean 'dubbo' while setting bean property 'protocols' with key [0]; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'dubbo' available**
===2018-11-09 15:44:01.329 INFO org.springframework.jmx.export.annotation.AnnotationMBeanExporter Line:451 - Unregistering JMX-exposed beans on shutdown
===2018-11-09 15:44:01.445 INFO com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor Line:251 - class com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor was destroying!
===2018-11-09 15:44:01.450 INFO org.apache.catalina.core.StandardService Line:180 - Stopping service [Tomcat]

**Comment by carryxyh** [comment]
Pls see here https://github.com/apache/incubator-dubbo/issues/2695#issuecomment-433824243

**Comment by carryxyh** [comment]
Seems like this has been support on branch 2.6.x.

**Comment by carryxyh** [comment]
I mean that it has been fixed on the latest version of 2.6.x branch. Not all the version of 2.6.x.

**Comment by fuhao715** [comment]
> I mean that it has been fixed on the latest version of 2.6.x branch. Not all the version of 2.6.x.

OK,3Q。I'll try to update it

**Comment by carryxyh** [comment]
I will close this issue now.
Reopen it if necessary.
@fuhao715 Thx for your issue.

**Comment by fuhao715** [comment]
> I will close this issue now.
> Reopen it if necessary.
> @fuhao715 Thx for your issue.
update it to 2.6.4,  also have this problem.

==2018-11-13 17:50:35.250 INFO  com.alibaba.dubbo.config.spring.beans.factory.annotation.DubboConfigBindingBeanPostProcessor Line:85  - The properties of bean [name : protocol1] have been binding by prefix of configuration properties : dubbo.protocols.protocol1
===2018-11-13 17:50:35.255 INFO  com.alibaba.dubbo.config.spring.beans.factory.annotation.DubboConfigBindingBeanPostProcessor Line:85  - The properties of bean [name : protocol2] have been binding by prefix of configuration properties : dubbo.protocols.protocol2
===2018-11-13 17:50:35.974 INFO  org.springframework.boot.devtools.autoconfigure.OptionalLiveReloadServer Line:57  - LiveReload server is running on port 35729
===2018-11-13 17:50:35.997 WARN  com.alibaba.dubbo.config.spring.extension.SpringExtensionFactory Line:63  -  [DUBBO] No spring extension(bean) named:defaultCompiler, try to find an extension(bean) of type java.lang.String, **dubbo version: 2.6.4,** current host: 192.169.20.250
===2018-11-13 17:50:35.997 WARN  com.alibaba.dubbo.config.spring.extension.SpringExtensionFactory Line:77  -  [DUBBO] No spring extension(bean) named:defaultCompiler, type:java.lang.String found, stop get bean., dubbo version: 2.6.4, current host: 192.169.20.250
===2018-11-13 17:50:36.107 WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext Line:558 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ServiceBean:defaultDemoService:com.swift.boot.dubbo.demo.api.DemoService:${demo.service.version}': Cannot resolve reference to bean 'dubbo' while setting bean property 'protocols' with key [0]; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'dubbo' available
===2018-11-13 17:50:36.112 INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter Line:451 - Unregistering JMX-exposed beans on shutdown
===2018-11-13 17:50:36.227 INFO  com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor Line:251 - class com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor was destroying!
===2018-11-13 17:50:36.234 INFO  org.apache.catalina.core.StandardService Line:180 - Stopping service [Tomcat]
===2018-11-13 17:50:36.249 INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener Line:101 -

**Comment by carryxyh** [comment]
> I mean that it has been fixed on the latest version of 2.6.x branch. 

2.6.x is not the latest version of 2.6.x.
The latest version is 2.6.5-SNAPSHOT

**Comment by fuhao715** [comment]
> > I mean that it has been fixed on the latest version of 2.6.x branch.
> 
> 2.6.4 is not the latest version of 2.6.x.
> The latest version is 2.6.5-SNAPSHOT

OK,Let me try

**Comment by fuhao715** [comment]
> > I mean that it has been fixed on the latest version of 2.6.x branch.
> 
> 2.6.4 is not the latest version of 2.6.x.
> The latest version is 2.6.5-SNAPSHOT
> 
> But 2.6.5-SNAPSHOT is not a release version. U can reproduce this problem in source code.

update it to 2.6.5, also have this problem.

 ===2018-11-26 15:42:52.405 INFO  com.alibaba.dubbo.config.spring.beans.factory.annotation.DubboConfigBindingBeanPostProcessor Line:86  - The properties of bean [name : protocol1] have been binding by prefix of configuration properties : dubbo.protocols.protocol1
===2018-11-26 15:42:52.411 INFO  com.alibaba.dubbo.config.spring.beans.factory.annotation.DubboConfigBindingBeanPostProcessor Line:86  - The properties of bean [name : protocol2] have been binding by prefix of configuration properties : dubbo.protocols.protocol2
===2018-11-26 15:42:53.244 WARN  com.alibaba.dubbo.config.spring.extension.SpringExtensionFactory Line:63  -  [DUBBO] No spring extension (bean) named:defaultCompiler, try to find an extension (bean) of type java.lang.String, dubbo version: 2.6.5, current host: 192.169.20.250
===2018-11-26 15:42:58.285 WARN  com.alibaba.dubbo.config.spring.extension.SpringExtensionFactory Line:81  -  [DUBBO] No spring extension (bean) named:defaultCompiler, type:java.lang.String found, stop get bean., dubbo version: 2.6.5, current host: 192.169.20.250
===2018-11-26 15:42:58.483 WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext Line:558 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ServiceBean:com.swift.api.demo.DemoService:1.0.0': Cannot resolve reference to bean 'dubbo' while setting bean property 'protocols' with key [0]; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'dubbo' available
===2018-11-26 15:42:58.492 INFO  org.springframework.jmx.export.annotation.AnnotationMBeanExporter Line:451 - Unregistering JMX-exposed beans on shutdown
===2018-11-26 15:42:58.617 INFO  com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor Line:286 - class com.alibaba.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor was destroying!
===2018-11-26 15:42:58.621 INFO  org.apache.catalina.core.StandardService Line:180 - Stopping service [Tomcat]
===2018-11-26 15:42:58.640 INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener Line:101 - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
===2018-11-26 15:42:58.696 ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter Line:42  - 

***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean named 'dubbo' that could not be found.


Action:

Consider defining a bean named 'dubbo' in your configuration.

===2018-11-26 15:42:59.491 INFO  com.alibaba.dubbo.config.DubboShutdownHook Line:56  -  [DUBBO] Run shutdown hook now., dubbo version: 2.6.5, current host: 192.169.20.250
===2018-11-26 15:42:59.493 INFO  com.alibaba.dubbo.registry.support.AbstractRegistryFactory Line:64  -  [DUBBO] Close all registries [], dubbo version: 2.6.5, current host: 192.169.20.250
Disconnected from the target VM, address: '127.0.0.1:50004', transport: 'socket'

Process finished with exit code 1

**Comment by carryxyh** [comment]
@mercyblitz 
Could u pls have a look?

**Comment by GuldanChen** [comment]
why did you more question？




            
            
                
                    
                            
                                
                            
                            
                                陈大清
                            
                    
                        
                            
                                    邮箱：mccrea.jsk@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2018年11月26日 16:15，时无两丶 写道： @mercyblitz
Could u pls have a look?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apache/incubator-dubbo","title":"apache/incubator-dubbo","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/apache/incubator-dubbo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@carryxyh in #2781: @mercyblitz \r\nCould u pls have a look?"}],"action":{"name":"View Issue","url":"https://github.com/apache/incubator-dubbo/issues/2781#issuecomment-441552021"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/incubator-dubbo/issues/2781#issuecomment-441552021",
"url": "https://github.com/apache/incubator-dubbo/issues/2781#issuecomment-441552021",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [apache/incubator-dubbo] dubbo配置支持多协议，不能在service指定其中某一种协议--附详细错误提示 (#2781)",
"sections": [
{
"text": "",
"activityTitle": "**时无两丶**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@carryxyh",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"apache/incubator-dubbo\",\n\"issueId\": 2781,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"apache/incubator-dubbo\",\n\"issueId\": 2781\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/apache/incubator-dubbo/issues/2781#issuecomment-441552021"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 409781448\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by GuldanChen** [comment]
不好意思发错了




            
            
                
                    
                            
                                
                            
                            
                                陈大清
                            
                    
                        
                            
                                    邮箱：mccrea.jsk@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2018年11月26日 19:42，陈大清 写道： 
why did you more question？




            
            
                
                    
                            
                                
                            
                            
                                陈大清
                            
                    
                        
                            
                                    邮箱：mccrea.jsk@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2018年11月26日 16:15，时无两丶 写道： @mercyblitz
Could u pls have a look?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apache/incubator-dubbo","title":"apache/incubator-dubbo","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/apache/incubator-dubbo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@carryxyh in #2781: @mercyblitz \r\nCould u pls have a look?"}],"action":{"name":"View Issue","url":"https://github.com/apache/incubator-dubbo/issues/2781#issuecomment-441552021"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/incubator-dubbo/issues/2781#issuecomment-441552021",
"url": "https://github.com/apache/incubator-dubbo/issues/2781#issuecomment-441552021",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [apache/incubator-dubbo] dubbo配置支持多协议，不能在service指定其中某一种协议--附详细错误提示 (#2781)",
"sections": [
{
"text": "",
"activityTitle": "**时无两丶**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@carryxyh",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"apache/incubator-dubbo\",\n\"issueId\": 2781,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"apache/incubator-dubbo\",\n\"issueId\": 2781\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/apache/incubator-dubbo/issues/2781#issuecomment-441552021"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 409781448\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by GuldanChen** [comment]
great



            
            
                
                    
                            
                                
                            
                            
                                陈大清
                            
                    
                        
                            
                                    邮箱：mccrea.jsk@gmail.com
                            
                        
                
            
        签名由 网易邮箱大师 定制


在2018年11月26日 16:15，时无两丶 写道： @mercyblitz
Could u pls have a look?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/apache/incubator-dubbo","title":"apache/incubator-dubbo","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/apache/incubator-dubbo"}},"updates":{"snippets":[{"icon":"PERSON","message":"@carryxyh in #2781: @mercyblitz \r\nCould u pls have a look?"}],"action":{"name":"View Issue","url":"https://github.com/apache/incubator-dubbo/issues/2781#issuecomment-441552021"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/apache/incubator-dubbo/issues/2781#issuecomment-441552021",
"url": "https://github.com/apache/incubator-dubbo/issues/2781#issuecomment-441552021",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [apache/incubator-dubbo] dubbo配置支持多协议，不能在service指定其中某一种协议--附详细错误提示 (#2781)",
"sections": [
{
"text": "",
"activityTitle": "**时无两丶**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@carryxyh",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"apache/incubator-dubbo\",\n\"issueId\": 2781,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"apache/incubator-dubbo\",\n\"issueId\": 2781\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/apache/incubator-dubbo/issues/2781#issuecomment-441552021"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 409781448\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by zhangxiongbiao** [comment]
`@Service` 注解中的注释提到，属性 `protocols` 的值需要对应配置的 `spring bean name` ，这个在 `application.yml` 中指定，例如：

```yaml
dubbo:
  protocol:
    id: dubbo
```

**Comment by gMan1990** [comment]
@carryxyh 借楼问下 `defaultCompiler, type:java.lang.String` 是啥？
