### ISSUE TITLE
dubbo 2.6.2版本中@Service注解的parameters配置BUG

### ISSUE THREAD

**Issue by gMan1990** [apache/dubbo#3072]
网文，不是我的: https://blog.csdn.net/xiao_jun_0820/article/details/81218440
我测过2.6.3, 2.6.5也是同样问题，其它新版本不知道

**Comment by lexburner** [comment]
@gMan1990 

1. 使用 parameter 配置 dubbo 的接口行为，有点 hack 的味道，自然不是 dubbo 推荐的行为，并不能认为是 dubbo 的 bug.
2. 目前注解的配置能力的确不如 xml 那么完备，后续应该会有支持。

可以的话，欢迎你的 pr 来完善方法级别的注解配置。

**Comment by GitFree** [comment]
2.6.x的最新2.6.9版本依旧有此问题

**Comment by pinxiong** [comment]
I have checked the Dubbo version both `2.7.x` and `2.6.x`, because this issue was raised a year ago.

for `2.7.x`, there is no such problem, because the `DubboService#parameters` was parsed in [ServiceClassPostProcessor](https://github.com/apache/dubbo/blob/master/dubbo-config/dubbo-config-spring/src/main/java/org/apache/dubbo/config/spring/beans/factory/annotation/ServiceClassPostProcessor.java#L417). Also, I have added some testcases, see #8001 

However, I have found this issue was still existed in `2.6.x`, I have fixed it and added some testcases, see #8002
