### ISSUE TITLE
dubbo接口缓存的问题

### ISSUE THREAD

**Issue by ericWenjp** [apache/dubbo#3689]
- [ ] I have searched the [issues](https://github.com/apache/incubator-dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/incubator-dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.4.9-sp5-20150715
* Operating System version: linux
* Java version: 1.5

### Steps to reproduce this issue

1. 在dubbo:refrence 中配置了cache=“LRU”,发现数据无法获取最新数据，有时候取到新的，有时候取到旧的，后来将cache配置删了，发现还是无法解决；
2. 通过调试，用命令trace dubbo接口，发现接口返回的数据中每次都是最新的，但是在程序中debug获取的返回值却是旧的，搞不懂了，为什么会与trace返回的数据不一样呢？

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

正常理解是cache去除后，应该是不走缓存？还是说配置问题？
是否会有缓存的序列化的问题，如果有，怎么清除序列化文件？

### Actual Result

```
![image](https://user-images.githubusercontent.com/25905832/54585896-59751900-4a56-11e9-8878-8457ae76cb69.png)
![image](https://user-images.githubusercontent.com/25905832/54585950-7dd0f580-4a56-11e9-87e3-dfee68a43861.png)

```

**Comment by cvictory** [comment]
I will try to reproduce this issue.

**Comment by cvictory** [comment]
After run sample, I found it work well. 

You can refer: https://github.com/apache/incubator-dubbo-samples/tree/master/dubbo-samples-cache . In this sample, you can modify loop times to more than 1000.  Then it will show the situation of cache invalid.

Also you can debug : org.apache.dubbo.cache.support.lru.LruCache .

After these operations, the issue is still exist.  You can upload a demo to us.
