### ISSUE TITLE
It is the dubbo protocol has been deprecated on version 2.6.5 ?

### ISSUE THREAD

**Issue by itfinally** [apache/dubbo#4251]
exception message:
  Caused by: com.alibaba.dubbo.rpc.RpcException: Failed to invoke the method xxx
  No such extension com.alibaba.dubbo.common.serialize.Serialization by name dubbo

I have two project running and communication with dubbo

Source dubbo version: 2.6.5 ( Java 8 ) no specify protocol serialization
Dest dubbo version: 2.5.3 ( Java 7 ) specify dubbo serialization
OS: just CentOS 7

So, It is the dubbo protocol has been deprecated on version 2.6.5 ?
Because I reading dubbo source code and found the class DubboSerialization at version 2.5.3 but not in version 2.6.5.

It is any way to resolve this protocol issue and migration ?

**Comment by web1992** [comment]
I think the `DubboSerialization` was deleted.

You catch exception because the `DubboSerialization` deleted. Dubbo can`t find the SPI in the classpath. 

You can write one by yourself

You can copy  `DubboSerialization` to your project.

write config like this

> fileName

META-INF/dubbo/om.alibaba.dubbo.common.serialize.Serialization

> file content

```
dubbo=your.package.name.DubboSerialization 
```

config xml

```xml
<dubbo:protocol serialization="dubbo" />
```

You can find SPI usage here [SPI serialize](http://dubbo.apache.org/zh-cn/docs/dev/impls/serialize.html)

**Comment by beiwei30** [comment]
try not specify 'dubbo' as serialization.
