### ISSUE TITLE
[Development Experience] support specifying protocols or registries directly

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#4626]
To simplify configuration, we should support specifying protocols or registries directly like the following:

```xml
<dubbo:consumer protocol="hessian" />
<dubbo:service interface="io.grpc.examples.helloworld.GreeterGrpc$IGreeter" ref="greeter" protocol="hessian"/>
```

Another related issue, we may also need to figure out the way of recognizing "the default registries or protocols".

**Comment by sonymoon** [comment]
Do you mean that even without `dubbo:protocol` configured, we can still recognize the final `protocol`
in `dubbo:consumer` `dubbo:service` or the `dubbo:provider` attribute by configuatrion priority of dubbo.
I tested in the current master branch, without `dubbo:protocol` configured, the protocol is default `dubbo`, but not expected because I also specified protocol(`hessian`) in `dubbo:service`.

I volunteer to rise a PR.
