### ISSUE TITLE
dubbo nacos版本的服务发现  dubbo.registry.group配置无效 

### ISSUE THREAD

**Issue by bigsmoke9527** [apache/dubbo#5978]
### Environment

* Dubbo version: dubbo-registry-nacos 2.7.6
* Operating System version: Win10
* Java version: JAVA 8

### Steps to reproduce this issue
1 springboot  yml配置如下： 
registry:
     address: nacos://127.0.0.1:8848
     simplified: true
     group: dubbo-local
  metadata-report:
            address: nacos://127.0.0.1:8848
            group: dubbo-local

2 登陆nacos 1.2.1 控制台发现元数据 group配置生效，但是服务管理下的group依旧是DEFAULT_GROUP。

3 跟了下dubbo-registry-nacos 2.7.6的代码 发现在调用NamingService中 没有传入配置的group参数，使用的默认组参数 
 public void doRegister(URL url) {
        String serviceName = this.getServiceName(url);
        Instance instance = this.createInstance(url);
        this.execute((namingService) -> {
            namingService.registerInstance(serviceName, instance);
        });
    }

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by Huangxuny1** [comment]
the reason of this issue is 
register group request  `group` key is `groupName` Instead of `group`

### groupName

>  curl -X PUT 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=example&groupName=group&ip=127.0.0.1&port=8080'

![image](https://user-images.githubusercontent.com/21981606/78869938-e9c63780-7a77-11ea-99c1-fa8d427b7c6a.png)

### group

> curl -X PUT 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=example-group&group=group&ip=127.0.0.1&port=8080'

![image](https://user-images.githubusercontent.com/21981606/78870032-10846e00-7a78-11ea-8751-0c3159a768a4.png)

I haven't verified in the code yet. I'll try it when I go home at night
