### ISSUE TITLE
Dubbo support Kubernetes Native Service

### ISSUE THREAD

**Issue by chickenlj** [apache/dubbo#6196]
# Dubbo support Kubernetes Native Service

基于 2.7.5 版本发布的应用级服务发现模型，对接 Kubernetes 原生服务，实现 Dubbo Consumer 自动发现 Kubernetes 服务。

## 背景

[Kubernetes Service](https://kubernetes.io/docs/concepts/services-networking/service/) 是 Kubernetes 平台对微服务模型的抽象，部署在 Kubernetes 平台之上的 POD 实例可被自动归类到虚拟的 Service 下，这样，部署在 Kubernetes 平台上的微服务消费者可实现对 Service Name 的直接依赖或调用，由 Kubernetes 平台实现流量从 Service 到 POD 节点的分发。

从 Dubbo 的角度，Service 到 POD 的映射关系相当于是一个自动化的服务注册过程，如果 Dubbo 作为消费方能自动解析这些 Kubernetes 服务，并将其纳入 Dubbo 的消费端的流量调度机制中，能很好的实现上层服务和底层基础设施的无缝整合。

![image](https://user-images.githubusercontent.com/18097545/82442850-0459ea80-9ad3-11ea-8d3a-be2eaaab0d82.png)

## 实现方案（目标） 

单独开一个 dubbo-kubernetes 子模块或项目

* 对接 DNS，实现与 Kubernetes Headless Service 的对接
* 对接 API-SERVER，参考 [spring-cloud-kubernetes](https://github.com/spring-cloud/spring-cloud-kubernetes)

**Comment by AlbumenJ** [comment]
Hi, I am a college student from China and hope I can make a little contribute to open-source. 
About this topic, I have a question that is whether there are some demos to learn about application-level service discovery model. I see that the model of `ServiceDiscoveryRegistry` has been added since 2.7.5, but I can't use it correctly.
After I configured the protocol as `service-discovery-registry`, the correct protocol that actually implements` ServiceDiscovery` cannot be obtained in the `ServiceDiscoveryRegistryFactory`.

关于这道题我有一点不清楚的是 2.7.5 发布的应用级服务发现模型是否有相关的 demo 可以学习。我看到从 2.7.5 版本以后加入了 `ServiceDiscoveryRegistry` 的模型，但是我找不到相关的能正常调用的方法。
当我配置协议为 `service-discovery-registry` 后，在 `ServiceDiscoveryRegistryFactory` 里面无法获取到正确的真正实现 `ServiceDiscovery` 的协议。

```
public class ServiceDiscoveryRegistryFactory extends AbstractRegistryFactory {

    @Override
    protected Registry createRegistry(URL url) {
        if (SERVICE_REGISTRY_PROTOCOL.equalsIgnoreCase(url.getProtocol())) {
            String protocol = url.getParameter(REGISTRY_KEY, DEFAULT_REGISTRY);
            url = url.setProtocol(protocol).removeParameter(REGISTRY_KEY);
        }
        return new ServiceDiscoveryRegistry(url);
    }

}
```
