### ISSUE TITLE
参数验证-验证信息被丢弃

### ISSUE THREAD

**Issue by harvies** [apache/dubbo#6199]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.7
* Operating System version: MacOS 10.14.6
* Java version: 1.8.0_231

### Steps to reproduce this issue

1. 参数验证信息被吞掉了

https://github.com/apache/dubbo-samples/blob/master/java/dubbo-samples-validation/src/main/java/org/apache/dubbo/samples/validation/ValidationConsumer.java

### Expected Result

What do you expected from the above steps？

### Actual Result

What actually happens?

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

![image](https://user-images.githubusercontent.com/16585330/82537560-d03b0400-9b7c-11ea-8f34-d8bdc080519a.png)
![image](https://user-images.githubusercontent.com/16585330/82537804-37f14f00-9b7d-11ea-92fa-02054d0f99df.png)

https://github.com/apache/dubbo/issues/5432

**Comment by harvies** [comment]
![image](https://user-images.githubusercontent.com/16585330/82549680-e1d9d700-9b8f-11ea-9323-e868a22fdb80.png)
去掉catch (ValidationException e) {}正常，序列化问题是否可以用其他方式修复

**Comment by carteruu** [comment]
mark

**Comment by CrazyHZM** [comment]
@stone-98 Any progress？

**Comment by stone-98** [comment]
@CrazyHZM I've been a little busy lately. I'll take care of it.

**Comment by stone-98** [comment]
I found that ValidationFilter did not work.

**Comment by stone-98** [comment]
In version 2.7.7，I found that it worked fine.
![image](https://user-images.githubusercontent.com/35629966/139924316-07d4783d-8452-41f1-b6db-aff2873b0dfc.png)

**Comment by stone-98** [comment]
No problem was found.

**Comment by lamyoung** [comment]
I think @harvies means "new ValidationException(e.getMessage())" cause violations of ConstraintViolationException lost, consumer only get message like ""
![image](https://user-images.githubusercontent.com/20555382/151661037-74e02417-76e8-4152-8ef3-b1f7d29415bc.png)

**Comment by lamyoung** [comment]
![image](https://user-images.githubusercontent.com/20555382/151661346-3afcbf1e-ad68-46b4-bea1-016e33d4d4d8.png)
@stone-98 @CrazyHZM 
The problem of "new ValidationException(e.getMessage())" as shown in fig causes lost of stack trace of origin exception, what means here losing violations of ConstraintViolationException. consumer only get message like
![image](https://user-images.githubusercontent.com/20555382/151661491-1c6fdedd-ecce-4e56-9366-23b5cb131346.png)
rather than 
![image](https://user-images.githubusercontent.com/20555382/151661444-1aa64024-34c3-4cda-959c-31af9cc46abe.png)
It is difficult to get 'some error message' from this compared to violations of ConstraintViolationException.
@harvies right?
An application scenario is to display the error message on the web page. This is unfriendly
![image](https://user-images.githubusercontent.com/20555382/151661491-1c6fdedd-ecce-4e56-9366-23b5cb131346.png)
