### ISSUE TITLE
How to use @DubboReference annotations Like xml and the basic attributes are only configured once?

### ISSUE THREAD

**Issue by yuxiao97** [apache/dubbo#6611]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [x] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: dubbo-spring-boot-starter:2.7.7
* Operating System version: MAC OS 10.15.6
* Java version: java 8

### Steps to reproduce this issue
How to use @DubboReference annotations Like xml, the basic attributes are only configured once, instead of configuring the same attributes for each reference.

**Comment by yuxiao97** [comment]
I reference dubbo service in same JavaConfig class, then @Autowired  in used class, but in used class tips no beans found of the type, even I use interfaceName in @DubboReference and use @Qualifier, the same  result with before.

**Comment by yuxiao97** [comment]
> I reference dubbo service in same JavaConfig class, then @Autowired in used class, but in used class tips no beans found of the type, even I use interfaceName in @DubboReference and use @qualifier, the same result with before.

When use  JavaConfig then start failed: 
`Field AAAService in BBBServiceImpl required a bean of type 'AAAService' that could not be found.

The injection point has the following annotations:
        - @org.springframework.beans.factory.annotation.Autowired(required=true)`

**Comment by JasonMing** [comment]
This is an annoying behavior.

Since 2.7.5 (maybe), `@DubboReference` cache the generated stub and register into spring application context.

But, if you do this in the `@Configuration` class, will break the dependency graph, because there is no `@Bean` method to tell spring should initialize the java config class before your service class.

To solve this problem, temporary, should put a `@DependsOn("javaConfigClassBeanName")` onto you service class to fix the broken dependency graph.

However, this solution is not elegant enough. The best way is separate dubbo reference declaration and injection.

**Comment by yuxiao97** [comment]
I use JavaConfig as SpringBean, than use @DubboReference reference Dubbo service and declcare Dubbo service as Bean, like this:
```
@Configuration
public class DubboServiceReferenceConfig {

    @DubboReference(version = "${dubbo.application.version}", check = false)
    private UserInfoService userInfoService;

    @Bean
    public UserInfoService userInfoService() {
        return userInfoService;
    }
    
}
```
