### ISSUE TITLE
readme中的链接有误

### ISSUE THREAD

**Issue by changfubai** [apache/dubbo#7031]
readme中的链接有误，点击404
![image](https://user-images.githubusercontent.com/20989201/102438482-578b2000-4057-11eb-937a-4f4b3a81fb63.png)
还有别的链接也无法使用，截图没有截完整~

**Comment by htynkn** [comment]
fixed part of them https://github.com/apache/dubbo/pull/6949

**Comment by changfubai** [comment]
I fixed the rest of them in #7037 but expect `Architecture` image and `Your first Dubbo application` link, as i can not find the source url.

[Architecture](https://github.com/apache/dubbo#architecture)

[Your first Dubbo application](https://github.com/apache/dubbo#next-steps)

cannot upload screen shot, put link there, someone know the source?

**Comment by changfubai** [comment]
> I fixed the rest of them in #7037 except `Architecture` image and `Your first Dubbo application` link, as i could not find the source url.
> 
> [Architecture](https://github.com/apache/dubbo#architecture)
> 
> [Your first Dubbo application](https://github.com/apache/dubbo#next-steps)
> 
> I cannot upload screen shot, put links here, does anyone know the source?

help?!

**Comment by kacperfronc** [comment]
@changfubai 
Hello. I'm not the dubbo dev but I see that you didn't get a reply and found that in the web archieve:
"Your first Dubbo application" was moved to http://dubbo.apache.org/blog/2018/08/07/dubbo-101/


The "architecture" image is:
![Architecture](https://i.imgur.com/cq5kJhy.png)

Please note, that I downloaded this image using web archive and uploaded this myself to imgur, so that link can't be used directly. There is an alternative to that image, which is here:
https://dubbo.apache.org/docs/v2.7/user/preface/architecture/
But I think it's fair to say it looks a bit worse

**Comment by changfubai** [comment]
> @changfubai
> Hello. I'm not a dubbo dev but I see that you didn't get a reply and I think I found the answers by browsing the repo page in the web archive:
> "Your first Dubbo application" was moved to http://dubbo.apache.org/blog/2018/08/07/dubbo-101/
> 
> The "architecture" image is:
> ![Architecture](https://camo.githubusercontent.com/5d3ca5fd6d95b664760be43641558fd7f468959e0d4974415583bd80284e3015/68747470733a2f2f692e696d6775722e636f6d2f6371356b4a68792e706e67)
> 
> Please note, that this is hosted by github and I'm not sure it can (well, it can but I don't think it should) be used directly in docs. There is an alternative to that image, which is here:
> https://dubbo.apache.org/docs/v2.7/user/preface/architecture/
> But I think it's fair to say it looks a bit worse

awesome!!!
why don't you try to pull request? I think it will work. Maybe I can do it if you think it is a trouble.
By the way, your "architecture" image is cool, dubbo dev will adopt it in Official doc?

**Comment by kacperfronc** [comment]
@changfubai
Absolutely no trouble! But since you started this issue and wanted to go ahead with those changes I don't want to get into the thing you started. Go ahead with those :)
The image itself isn't mine, it was there like that in README, the broken link was pointing to this image exactly, it's just that for some reason the dubbo.apache.org shows the older one, not sure why.

**Comment by changfubai** [comment]
@kacperfronc 
Thanks, I'll do it. 
Nice to meet you, I learnt a lot from you. I contributed to open-source recently and got a lot of growth, thanks again.

**Comment by changfubai** [comment]
fixed in pr #7072
