### ISSUE TITLE
dubbo demo中没有用到dubbo-registry-kubernetes，而且dubbo-config中没有k8s的对接

### ISSUE THREAD

**Issue by lizhiqiang123321** [apache/dubbo#7240]
### Environment

* Dubbo version: 3
* Operating System version: kubernetes3
* Java version: 8

### Steps to reproduce this issue

1. dubbo3的dubbo-demo中，没有找到dubbo-registry-kubernetes
2. dubbo3的dubbo-demo中，没有找到dubbo-configcenter(如何与k8s对接)

Pls. provide [GitHub address] to reproduce this issue.

### Expected Result

和spring-cloud-kubernetes一样，解决了两个注册中心、两个配置中心的问题

**Comment by huyunhaode** [comment]
You can find a demo usinig dubbo-registry-kuubernetes in the project "apache/dubbo-samples".

**Comment by huyunhaode** [comment]
dubbo3 has not implemented the config center through the k8s.Maybe dubbo3 will implement the config center through the k8s.However,it seems not nesscessary to use the config center directly on k8s.Since the version 2.7.6,dubbo use Service Introspection(服务自省).One of the reason is decentralization(去中心化).The metadata is used to store in the registry before 2.7.4.Now dubbo provide a way to store the metadata in the provider,and one of the way for the consumer to get the metadata of providers is to use rpc to invoke the MetadataService of the providers.This way will reduce stress of the config center.However,using the MetadataService will stress the k8s much.It is recommented to use nacos or appolo as the config center in the production environment.

**Comment by CrazyHZM** [comment]
You can refer to the content of this project：https://github.com/apache/dubbo-samples
The above answer should solve your problem
