### ISSUE TITLE
WARN org.apache.dubbo.config.spring.beans.factory.config.DubboConfigEarlyInitializationPostProcessor CommonAnnotationBeanPostProcessor is not registered yet, the method addIntoConfigManager() will be invoked directly

### ISSUE THREAD

**Issue by NickZhang1024** [apache/dubbo#8052]
log WARN org.apache.dubbo.config.spring.beans.factory.config.DubboConfigEarlyInitializationPostProcessor CommonAnnotationBeanPostProcessor is not registered yet, the method addIntoConfigManager() will be invoked directly

how to resolve ?

**Comment by CrazyHZM** [comment]
The reason for this alarm log may be that your project does not use any annotations, such as @Resource annotations, to trigger bean loading. At this time, in order to ensure that the ConfigManage required in dubbo is initialized normally, addIntoConfigManager() will be executed automatically. If annotations are added, CommonAnnotationBeanPostProcessor will be created in the spring container, thereby triggering the addIntoConfigManager() method in CommonAnnotationBeanPostProcessor.
You can try to add some comments, or you can choose to ignore the log.
