### ISSUE TITLE
多注册中心环境下服务未去重

### ISSUE THREAD

**Issue by Yanniiii** [apache/dubbo#8506]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.
- [ ] I have checked the [FAQ](https://github.com/apache/dubbo/blob/master/FAQ.md) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 2.7.10
* Operating System version: win7
* Java version: 1.8

### Steps to reproduce this issue

provider和consumer通过 ‘dubbo:registry address="multiple://......’  配置了多个注册中心，比如一个Nacos，一个Zookeeper，provider向两个注册中心注册了自己的service，consumer在loadbalance.select()时会读取到同一服务在两个注册中心下两份相同的实例。

### Expected Result

不应该对未去重的实例进行负载均衡：loadbalance.select()读取到的应该是经过去重的实例，在上述例子中，应该只有一个。

**Comment by CrazyHZM** [comment]
The essence of this problem is the URL represented by the instance. How to judge whether it is equal?
Separate two versions to discuss,
2.7.x: The URL does have the problem discussed above, that is, different registries carry different parameters, which makes it more difficult to deduplicate the URL.
3.x: In 3.x, we introduced a multi-instance design, whether it is possible to bind an instance when subscribing, that is, the interface name, group, and version are no longer the only conditions, and Framework, Application must also be added. , Module can determine uniqueness.
