### ISSUE TITLE
Potential RpcServiceContext contamination in Dubbo 3

### ISSUE THREAD

**Issue by wu-sheng** [apache/dubbo#9666]
- [x] I have searched the [issues](https://github.com/apache/dubbo/issues) of this repository and believe that this is not a duplicate.

### Environment

* Dubbo version: 3.x
* Operating System version: xxx
* Java version: xxx

### Steps to reproduce this issue

The whole discussion context could be found in this SkyWalking's bug report, https://github.com/apache/skywalking/issues/8525
According to the discussion, when a service acts as a provider and consumer at the same time, `serviceContext.isConsumerSide();` always returns **true** even it is already in the customer calling context.

Pls. provide [GitHub address] to reproduce this issue.

### Expected Behavior

`serviceContext.isConsumerSide();` works as expected, even it is in a `provider->internal logic->consumer` in-process scenario.

### Actual Behavior

If there is an exception, please attach the exception trace:

```
Just put your stack trace here!
```

**Comment by chickenlj** [comment]
We will try to figure out this issue in the next major release

**Comment by wu-sheng** [comment]
@honganan Let's wait for a solution here, no matter this should be fixed on skywalking or dubbo.

**Comment by honganan** [comment]
> @honganan Let's wait for a solution here, no matter this should be fixed on skywalking or dubbo.

ok

**Comment by wu-sheng** [comment]
Any update from Dubbo community?

**Comment by wu-sheng** [comment]
We did full research on https://github.com/apache/skywalking-java/pull/110, which is ready to merge soon.
I want to update the Dubbo community, this is a bug for sure. We are using a bypass to check whether it is a provider side or a consumer side, and avoid using the native context's status only.

But this would affect other users too. It is better Dubbo could fix this. SkyWalking community will keep in this bypass solution, to make sure all existing previous releases(before your fix) could work well with our agent.

**Comment by AlbumenJ** [comment]
Will be fix in #9740

**Comment by honganan** [comment]
> Will be fix in #9740

That's nice!

**Comment by wu-sheng** [comment]
> > Will be fix in #9740
> 
> That's nice! After that we will change to invoking Dubbo api directly.

This may be tricky, because adopt native API means breaking the previous version support, unless you add new witness class as well as new interceptor, your call.

**Comment by honganan** [comment]
That’s a problem


------------------ Original ------------------
From: 吴晟 Wu Sheng ***@***.***&gt;
Date: Mon,Mar 7,2022 11:46 AM
To: apache/dubbo ***@***.***&gt;
Cc: 洪阿南 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [apache/dubbo] Potential RpcServiceContext contamination in Dubbo 3 (Issue #9666)





   
Will be fix in #9740
  
That's nice! After that we will change to invoking Dubbo api directly.
  
This may be tricky, because adopt native API means breaking the previous version support, unless you add new witness class as well as new interceptor, your call.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
